### ISSUE TITLE
undefined reference to 'driver_list::s_drivers_sorted'

### ISSUE THREAD

**Issue by mzbab88** [Robbbert/mameui#22]
Trying to compile this https://github.com/Robbbert/mameui/tree/mame0147u4

(This is the version I currently have on my computer, downloaded it a few years ago, and newest version looked kinda buggy, so went for an older one. Not sure if I should've tried mame0147 instead of mame0147u4)

I'm getting error when trying to link mame.exe. In src\emu\drivenum.c and src\emu\drivenum.h, there exist declaration of s_drivers_sorted, but no implementation of it. Tried to just copy declaration from .h to .c, but it didn't work. Any idea what I can do with it?

I'm trying to compile it because I want to add gui for playing mame replays.

**Comment by mzbab88** [comment]
Version from 2012 was 70 MiB, current version is 170 MiB. You've been bisy, it seems.

New version resized one of it's panels weirdly, but it seems to be ok now. I'll try to compile it next.

**Comment by Robbbert** [comment]
You might need to include drivnum.h

In any case, we don't offer support of old versions.
