### ISSUE TITLE
Program closes suddenly

### ISSUE THREAD

**Issue by exeron** [Robbbert/mameui#23]
I noticed two problems:

1- When starts, I always get the next message besides the directories/files exist:

MAMEUI64: Error parsing D:\torrent\MAME 0.186 EXTRAs\folders\nplayers.ini: missing [folder name] or [ROOT_FOLDER]

Program loads anyway.

2. After browsing some seconds in different roms, mameui closes without any message. It happens randomly but happens 100% of times.
Nothing is touched, nothing is modified, just start program, click on desired list of categories and browse in the entries for that category using keyboard.

In some tests I could notice: 
-Before closing the program slows down, hougarglass appear (or looks busy) and keeps like that until closes.
-Any change in window layout (ie: resizing the list areas) is not saved so next execution will show the previous state. But changes in Options menu, are saved.

I enabled the debug options to save in file, etc. but got nothing. 'debug.txt' file doesn't show anything only the message of issue 1.

If there is anything I can do to collect more debug data, please tell me.

I'm using OS Windows 7 x64 Home Premium.
MameUI version using is 0.186 downloaded from next link: http://www.mameui.info/MameUI64.7z

**Comment by Robbbert** [comment]
Seems your players.ini is corrupt.

**Comment by exeron** [comment]
I checked the players.ini following your suggestion.

Browsing on the Internet I noticed they are two kind of players.ini one for mame and other compatible with mameui (I'm not expert on players.ini). I was using the former.
Replacing the original players.ini by the "compatible" version with MameUI removed the error message, and mameui shows the related folder. Structure of ini files is different.

Source of players.ini:  http://nplayers.arcadebelgium.be/

- http://nplayers.arcadebelgium.be/files/nplayers0186.zip  ==> error with MameUI
- http://nplayers.arcadebelgium.be/files/nplayers32_0186.zip  ==> loads correctly

**Comment by exeron** [comment]
#Issue 2: **MameUI closing**  suddenly.

I was unable to locate the problem but after fixing the "problem" with nplayers.ini and load it, I noticed MameUI closes if I select an specific folder. It also closes with other folders or files but behaviour is quite erratic and impossible to predict when it's going to close.

Now, with "fixed" nplayers.ini (just use the compatible iwith mameui), If you browse the folder list and select "nplayers->9P..." folder, MameUI closes inmediately. It happens 100% of times. I don't mean that nplayers.ini is the problem just with that file I could duplicate the issue in an exact unique point.

I uploaded two videos where you can see the problem in action and the nplayers.ini file used. Notice my desktop wallpaper is solid black. I hope this can help you to isolate the problem.


[mameui closing.zip](https://github.com/Robbbert/mameui/files/1112784/mameui.closing.zip)
