### ISSUE TITLE
MameUI closing when some folders are selected

### ISSUE THREAD

**Issue by exeron** [Robbbert/mameui#24]
I open MameUI (0.186) and after browsing some seconds in different roms, mameui closes without any message. It happens randomly but happens 100% of times.
Nothing is touched, nothing is modified, just start program, click on desired list of categories and browse in the entries for that category using keyboard.

In some tests I could notice: 
-Before closing the program slows down, hougarglass appear (or looks busy) and keeps like that until closes.
-Any change in window layout (ie: resizing the list areas) is not saved so next execution will show the previous state. But changes in Options menu, are saved.

I enabled the debug options to save in file, etc. but got nothing. 'debug.txt' file doesn't show anything only the message of issue 1.

If there is anything I can do to collect more debug data, please tell me.

I'm using OS Windows 7 x64 Home Premium.

**## Update:**
I was unable to locate the problem but after fixing the "problem" with nplayers.ini ( #23 ) and it is loaded, I noticed MameUI closes if I select a specific folder (it also closes with other folders or files but behaviour is quite erratic and impossible to predict).

Now, with "fixed" nplayers.ini (just use the compatible iwith mameui), If you browse the folder list and select "**nplayers->9P**..." folder, MameUI closes inmediately. It happens 100% of times. I don't mean that nplayers.ini is the problem just with that file I could duplicate the issue in an exact unique point.

**Attached** there are two **videos** where you can see the problem in action (and the nplayers.ini file used). Notice my desktop wallpaper is solid black, so when it closes all is in black. I hope this can help you to isolate the problem.

[mameui closing.zip](https://github.com/Robbbert/mameui/files/1112784/mameui.closing.zip)

**Comment by Robbbert** [comment]
Turns out it's nothing to do with NPlayers.ini, the problem is that Megatech games (all of them except the bios) crash MAMEUI when clicked on.

Looking into it...

**Comment by Robbbert** [comment]
This has been fixed, thanks for reporting it.
