### ISSUE TITLE
MAMEUI crash (0.188GIT)

### ISSUE THREAD

**Issue by MASHinfo** [Robbbert/mameui#25]
The new 0.188 GIT source crashed. The reason is the missing 'CreateBIOSFolders' function.
If you delete the line in layout.cpp the crash is gone!

Changed the line 98 in src\osd\winui\layout.cpp
from
	{"BIOS",            "bios",              FOLDER_BIOS,         IDI_FOLDER,               0,             0,            CreateBIOSFolders,          DriverIsBios,            TRUE },
to
//	{"BIOS",            "bios",              FOLDER_BIOS,         IDI_FOLDER,               0,             0,            CreateBIOSFolders,          DriverIsBios,            TRUE },

Here is the old 'CreateBIOSFolder' functions you deleted several versions before in src\osd\winui\treeview.cpp:

void CreateBIOSFolders(int parent_index)
{
	int i, jj;
	int nGames = driver_list::total();
	int start_folder = numFolders;
	const game_driver *drv;
	int nParentIndex = -1;
	LPTREEFOLDER lpFolder = treeFolders[parent_index];
	LPTREEFOLDER lpTemp;

	// no games in top level folder
	SetAllBits(lpFolder->m_lpGameBits,FALSE);

	for (jj = 0; jj < nGames; jj++)
	{
		if ( DriverIsClone(jj) )
		{
			nParentIndex = GetParentIndex(&driver_list::driver(jj));
			if (nParentIndex < 0) return;
			drv = &driver_list::driver(nParentIndex);
		}
		else
			drv = &driver_list::driver(jj);
		nParentIndex = GetParentIndex(drv);

		if (nParentIndex < 0 || !driver_list::driver(nParentIndex).type.fullname())
			continue;

		for (i = numFolders-1; i >= start_folder; i--)
		{
			if (strcmp(treeFolders[i]->m_lpTitle, driver_list::driver(nParentIndex).type.fullname()) == 0)
			{
				AddGame(treeFolders[i],jj);
				break;
			}
		}

		if (i == start_folder-1)
		{
			lpTemp = NewFolder(driver_list::driver(nParentIndex).type.fullname(), next_folder_id++, parent_index, IDI_CPU, GetFolderFlags(numFolders));
			AddFolder(lpTemp);
			AddGame(lpTemp,jj);
		}
	}
}

Another crash in 0.188GIT comes from the MAME\folders\Device.ini
from http://www.mameworld.info/mameinfo/download/MAMEUI-inifiles-0187.zip.
I must delete Device.ini, otherwise MAMEUI crashed!

-

**Comment by Robbbert** [comment]
The BIOS thing is because you removed the #MESS define. This configuration is not supported. As a matter of interest I added the deleted code, and it produces no output, so is useless.

I do not support individual folder/ini files. Device.ini evidently has a mistake in it somewhere. The maintainer of that file will need to fix it. For example there's a random character at the end, but removing it doesn't fix the issue. Perhaps it is too large.

**Comment by MASHinfo** [comment]
Ok! I will find out what happend with the Device.ini.

**Comment by MASHinfo** [comment]
I found the Device.ini problem:
MAMEUI don't like a dash sign (-) in brackets. No matter how long the Device.ini is.

Examples:
[IDE Controller (16-bit)]
[IDE Controller (32-bit)]
[Sharp LH28F016S Flash (16-bit)]
[Taito TC0030CMD (C-Chip)]

**Comment by Robbbert** [comment]
Found a fix for this, device.ini now works. Turns out it's a side-effect of the changes done to options processing in the core.

**Comment by MASHinfo** [comment]
Thx a lot!
