### ISSUE TITLE
MAMEUI did not show the MAMEinfo.dat for every game

### ISSUE THREAD

**Issue by MASHinfo** [Robbbert/mameui#26]
Since MAMEUI64 0.186, the MAMEinfo.dat will no longer displayed for every game.
Sort the games by 'Source' driver and for fieldday (40love.cpp) it displays
the MAMEinfo.dat but not for 40love (40love.cpp).
Or for 4roses (4roses.cpp) but not for rubgy (4roses.cpp).

Works in MAMEUI64 0.185!

**Comment by Robbbert** [comment]
Tested with current git, works correctly.

**Comment by MASHinfo** [comment]
Oh, i mean the 'Driver Section / SOURCE:' of every game at the end of the MAMEinfo.dat.
Can you please check it again!

**Comment by Robbbert** [comment]
This has been fixed.
