### ISSUE TITLE
Mameinfo.dat and Messinfo display

### ISSUE THREAD

**Issue by MASHinfo** [Robbbert/mameui#27]
To correct the Mameinfo.dat and Messinfo display with the extra "\r\n\r\n" characters:

Changed line 150 in src/osd/winui/history.cpp
from
		readbuf.append(file_line).append("\n");
to
		if (file_line.length())
			readbuf.append(file_line);
		else
			readbuf.append(file_line).append("\n");

-
Looks exactly as in the old 0.187 version

**Comment by Robbbert** [comment]
If that was done, then you couldn't add space between paragraphs. The intent is to present it exactly the way you have it in the .dat file, verbatim. If you have excessive space in your file, that's what you'll see.

**Comment by MASHinfo** [comment]
There are no spaces in my MAMEinfo.dat before any new line, then an exception has to be made.
Thx for clarifying that!

**Comment by Robbbert** [comment]
What I mean is that whatever you write in MAMEINFO.dat (or any of the dats) will be reflected exactly in MAMEUI. There's no need for extra blank lines and so on like the old days. If you want to add a blank line in the display, add a blank line in your .dat file.
