### ISSUE TITLE
MAMEUI don't list clone infos

### ISSUE THREAD

**Issue by MASHinfo** [Robbbert/mameui#28]
MAMEUI don't list the MAMEinfo.dat info for the clones.
For the parent set it list the "**** :MAMEINFO: ****" info, for the clones only
the "***:MAMEINFO DRIVER" info.

Examples:
Jungle King (alternate sound)
Jungle King (Japan, earlier)
Jungle King (Japan) => parent (list all)

**Comment by Robbbert** [comment]
This is fixed.
