### ISSUE TITLE
Loading of CTRL files does not make any difference to keys

### ISSUE THREAD

**Issue by a7mag3ddon** [Robbbert/mameui#29]
When Loading a controller ini file from the drop down menu in controllers (for example xbox 360 or X-Arcade or any custom made ones) the expected keys / pad buttons don't work and Mame stays as default.

Any more info needed please let me know.

**Comment by Robbbert** [comment]
I can't really test this because I don't have a controller. However, I right-clicked GBA and changed controller to xarcade, and it was remembered, and the keyboard controls changed. I don't have a xbox360 controller file. Then, I changed it back to Default (there's no Mame).

Next, I went to the Default System Options and selected xarcade, and it was also remembered. Of course it couldn't be tested because the individual game ini files override the System Options.

**Comment by Robbbert** [comment]
Nothing further heard, closing.

**Comment by a7mag3ddon** [comment]
Yes its remembered, but the controls don't work :-)

Set to xbox360 pad, shows xbox 360pad, doesnt work, change to xarcade, it shows xarcade doesnt work.

You can easily test by just changing some keys, its called a ctrl file but you can set keys instead of a game pad.

**Comment by a7mag3ddon** [comment]
I will test on the new version once the c++ issue has been looked at, maybe was just a bug on previous version.

**Comment by a7mag3ddon** [comment]
Ok sorted the C++ thing, controller ini still dont load when changed heres how you can test it for your self.

Go into CFG folder, delete the Default.cfg start mame, press tab select Input (General) change up/down/left/right to something like wasd and exit mame. move the default.cfg into CTRL folder call it WASD.cfg

restart mame, redefine Input (General) to cursor keys up/down/left/right again move default.cfg to CTRL folder and rename it CURSOR.

Now, start mame, select default system options then controller, or if you prefer just for that game, select CURSOR and play the game, cursor keys should move you left/right/up/down but they don't.

quit the game, change controller to WASD this time WASD should move you up/down/left/right... but they don't.

I did this with the genuine mame version and loading the 2 ctrl files works as it should, so does Arcade64 as well.

Hope this explains it a bit better.
