### ISSUE TITLE
Mameui x64 x86 both crash on startup (189)

### ISSUE THREAD

**Issue by a7mag3ddon** [Robbbert/mameui#30]
Hello,

Both new mameui 189 crash on startup with a c++ error 

This application has requested the runtime to terminate it in an unusual way. Please contact the applications support team for more information.

Are there some new libraries i need to get it to work ?

**Comment by hfball** [comment]
Move your mameui.ini and mame_g.ini files out of the MAME directory. Restart. You need to create new ini files, the format has changed.

**Comment by a7mag3ddon** [comment]
Thank you that has worked :-)

**Comment by a7mag3ddon** [comment]
Question, if an "issue" has been closed and i add comments to it, does the owner of the github see the new comments or do i need to open a new issue? (even if its more info on the old one) ?

**Comment by stewfir** [comment]
I had same issue and above resolved it. however not have issue where it does not recognised software list (hash files) - any suggestions eg is it me and need to configure mameui? works in normal mame.
thanks

**Comment by Robbbert** [comment]
I still see the new comments, but my ISP throws away many github emails, for example I didn't know this issue existed until now. It would be much better if you raised MAMEUI problems on the 1emulation forum, as I visit there every day. Now I'm closing this.

**Comment by a7mag3ddon** [comment]
Can you look into the other issue you closed? Its still there the one about controller files.
