### ISSUE TITLE
Loading of CTRL files in the last few version of MameUI dont work

### ISSUE THREAD

**Issue by a7mag3ddon** [Robbbert/mameui#31]
Im stating a new issue because i dont know if you see all the comments to the old one you closed a couple of weeks ago, i too didnt know you had responded, anyway here is how to show/ see whats not working.

Go into CFG folder, delete the Default.cfg start mame, press tab select Input (General) change up/down/left/right to something like wasd and exit mame. move the default.cfg into CTRL folder call it WASD.cfg

restart mame, redefine Input (General) to cursor keys up/down/left/right again move default.cfg to CTRL folder and rename it CURSOR.

Now, start mame, select default system options then controller, or if you prefer just for that game, select CURSOR and play the game, cursor keys should move you left/right/up/down but they don't.

quit the game, change controller to WASD this time WASD should move you up/down/left/right... but they don't.

I did this with the genuine mame version and loading the 2 ctrl files works as it should, so does Arcade64 as well.

Hope this explains it a bit better.

**Comment by Robbbert** [comment]
Followed what you said, step by step - and it worked as expected.

**Comment by a7mag3ddon** [comment]
Ok in that case i will have to ask on the Pleasure Dome fourums why mine isn't working, and if anyone else has the same issues, a couple of friends tested for me and there's didn't work either but i need a wider test panel i guess.

**Comment by a7mag3ddon** [comment]
I have made the post, if it is my installation why does Arcade64 work ok and MameUI not when they are in the same folder.

**Comment by a7mag3ddon** [comment]
Your right, i have done a fresh install with just a CFG, ROMS (and pacman) and the CTRLR folder and it is working, yet in its original location it does not, as the creator of MameUI do you know why that might be ? Im stuck now as i dont know whats causing it.

**Comment by Robbbert** [comment]
I do not know.
