### ISSUE TITLE
Another use of .reserve() over .resize()

### ISSUE THREAD

**Issue by BigJim** [Robbbert/mameui#34]
2nd use of ".reserve()" when it should be a ".resize()".

src\osd\winui\mui_util.cpp line #606
Change to:
`drivers_info.resize(driver_list::total()); `

Might have not shown up before using msys64 debug builds since I'm building with VS2107.  
It's maybe something msys64 that is tolerant (at run-time) about.  But then technically it should be "resize()" still.  
Also would be fine/legal if used "push_back" or "insert" instead of the index[] operator (albeit probably a bit slower in inner loops).

Looking at the remaining instances of "reserve(" this appears the last of them.

**Comment by Robbbert** [comment]
Fixed, thanks.
