### ISSUE TITLE
Passing any argument starts up Mameui with Mame's UI 

### ISSUE THREAD

**Issue by BigJim** [Robbbert/mameui#35]
In _winui.cpp_ inside _MameUIMain()_ there is this section:
```
if (__argc != 1)
	{
		/* Rename main because gcc will use it instead of WinMain even with -mwindows */
		extern int utf8_main(std::vector<string> &args);
		std::vector<string> utf8_argv(__argc);

		/* convert arguments to UTF-8 */
		for (int i = 0; i < __argc; i++)
			utf8_argv[i] = ui_utf8_from_wstring(__targv[i]);

		/* run utf8_main */
		exit(utf8_main(utf8_argv));
	}
```
Apparently back in pre Mame with-a-GUI days you could pass arguments to Mameui to make it behave like the old console way.
As it is now if you pass even one argument it causes a switch over to the Mame GUI.

Only experienced this because the default debug setup in Windows passes "-window" and thus triggered it.  

Could be fixed by parsing the arguments and handling things like "-window" et al to restore the previous behavior but IMHO not worth the effort as apparently no one runs it this way anyhow. 
I recommend just commenting it out or deleting the section entirely.  Also could go edit and play with  _scripts/src/osd/messui.lua_ removing Mame UI sources that aren't being used (then regenerate your platform makes) but that's some effort to just save a few KB in code/data size.

**Comment by Robbbert** [comment]
It's still a supported feature, so you can run a game directly without going through the GUI. If you want the GUI don't add any arguments.

**Comment by BigJim** [comment]
Understood.
