### ISSUE TITLE
0.191 and Xinput controller: Analog triggers + and - not "separated" any more

### ISSUE THREAD

**Issue by YesterPlay80** [Robbbert/mameui#36]
Since upgrading MAMEUI to 0.191 the analog triggers on both my gamepad (a Logitech F710) and my Xbox 360 racing wheel (the pedals) seems to "fade" into each other when in neutral. If none are pressed, the left one always seems to be active. Given that I use the left for braking and the right for accelerating in most racing games, the brakes (left trigger/pedal) are always active if I don't push the accelerator (right trigger/pedal). So I can't just lose speed by letting the gas go, because the brakes kick in immediately. Furthermore, if I have to select something with the gas pedal, I have to press both at first, releasing the left one then makes the selection.

I switched back to 0.190 and everything worked as it should, with the same configuration, so it seems to be a problem with this specific build.

**Comment by Robbbert** [comment]
What happens with official MAME 0.191 ? I haven't changed anything.

**Comment by YesterPlay80** [comment]
I think I found the "error" in the long list of changes for 0.191:

"Make xinput analog triggers half-axes and default IPT_PEDAL2 to RZ- instead of Z+, placing IPT_PEDAL and IPT_PEDAL2 on separate axes."

**Comment by Robbbert** [comment]
In that case, if you're sure it's actually a bug, log a report at mametesters.

Closing.
