### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gosub-com** [Robbbert/mameui#37]
I'm trying to build messui and getting an error (and also get the same error when compiling mameui):

GCC 7.2.0 detected
Precompiling src/emu/emu.h...
process_begin: CreateProcess(NULL, E:\Mingw\5-3-0\mingw64/bin/x86_64-w64-mingw32-g++ -MMD -MP -MP -DX64_WINDOWS_ABI -DPTR64=1 -DNDEBUG -DCRLF=3 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DWIN32 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -m64 -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override -flifetime-dse=1 -x c++-header -DX64_WINDOWS_ABI -DPTR64=1 -DNDEBUG -DCRLF=3 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DWIN32 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -o ../../../../mingw-gcc/obj/x64/Release/emu.h.gch -c ../../../../../src/emu/emu.h, ...) failed.
make (e=2): The system cannot find the file specified.
precompile.make:298: recipe for target '../../../../mingw-gcc/obj/x64/Release/emu.h.gch' failed
make[2]: *** [../../../../mingw-gcc/obj/x64/Release/emu.h.gch] Error 2
makefile:88: recipe for target 'precompile' failed
make[1]: *** [precompile] Error 2
makefile:1031: recipe for target 'windows_x64' failed
make: *** [windows_x64] Error 2

I am on Windows.  I followed the directions to compile mame, and sucessfully got that compiled and running.  Are there different build instructions for messui? 

Thank you,

Jeremy

**Comment by Robbbert** [comment]
No, it's all the same. It appears you're trying to use my make.bat when you should make your own.
