### ISSUE TITLE
How to remove or hide built-in games?

### ISSUE THREAD

**Issue by ahdung** [Robbbert/mameui#39]
![image](https://user-images.githubusercontent.com/12094247/66849172-08f07a80-efa9-11e9-86aa-b1227b54cd5b.png)

**Comment by ahdung** [comment]
@Robbbert All these games at right side are built-in games, or call it romless games, in MAME, has a option can hide them, MAMEUI also should can do.

**Comment by Robbbert** [comment]
MAMEUI cannot do that. It has no way to identify a "romless" game.

**Comment by ahdung** [comment]
@Robbbert all right, thanks
