### ISSUE TITLE
Interface does not scale according to scale and layout settings

### ISSUE THREAD

**Issue by Athiril** [Robbbert/mameui#43]
In Windows in settings under Display there is a Scale ad Layout section with "Change the size of text, apps, and other items", I have it set to 250%, mameui doesnt apply this to its interface.

Its important since my display is 4K, and the mameui interface becomes way too small on 4K resolution.

**Comment by jessicajonesunitedkingdom** [comment]
Confirmed here too on windows xp

**Comment by Robbbert** [comment]
Windows 10 specific features are not supported.
