### ISSUE TITLE
Loss of overlay and cpanel options on MISC menuy

### ISSUE THREAD

**Issue by a7mag3ddon** [Robbbert/mameui#47]
Not sure if this has been done on purpose, or if its me but i seem to have lost the ability to remove/ disable Overlays, Cpanels from the MISC tab in Mame UI. all i see now is a big space and at the bottom a tick box for Crop Overlays.

Has the way Overlays and things changed? I downloaded a prev version and did a fresh unzip into a new directory and thats the same as well.

**Comment by a7mag3ddon** [comment]
Just a quick update after some testing, i downloaded a few older versions starting with V 200 and it worked all the way up to 210 after that a couple of versions had Backdrop and Crop Overlay boxes then after i think 212 all the options were gone apart from one mentioned above (crop overlays).

**Comment by Robbbert** [comment]
The options were removed from the MAME core. That's why they had to be removed from MAMEUI too.

**Comment by a7mag3ddon** [comment]
Where were those particular settings saved? Maybe i still have them because im now told that bezels and art should be off by default anyway, perhaps my settings still have them turned on.

**Comment by Robbbert** [comment]
They were saved in mame.ini, or any other ini except mameui.ini .
Even if the settings are still in your files they will be ignored in recent versions.
