### ISSUE TITLE
MAMEUI64 has 1 software list more then MAME

### ISSUE THREAD

**Issue by mamecodemonkey** [Robbbert/mameui#48]
Dear MAMEUI64 dev,

I'm using MAME's -listsoftware output frequently and I found a very weird problem.

If you run -listsoftware on official MAME and save it to a XML file, you always have 1 software list LESS then doing the same on MAMEUI64. So MAMEUI64 has 1 software list added which is not inside MAME's -listsoftware output.

My questions:

- Why do you add 1 software list that's not inside MAME?

- What software list is added?

best regards

**Comment by Robbbert** [comment]
I have no idea what you are talking about. You will need to find out what extra list might be there.

**Comment by mamecodemonkey** [comment]
Run mame64.exe -listsoftware > listsoftware.xml

Then run MAMEUI64.exe -listsoftware > listsoftware.xml

Compare both files. The MAMEUI64 XML file has 1 software list MORE then mame64
That's what I'm talking about.

Since you are the developer, how is it possible you don't know 1 extra software list is added? 

best regards

**Comment by mamecodemonkey** [comment]
Hi

I compared both xml files using winmerge and I found mameui64 has a software list which was removed from mame: c64_flop.
It was removed from mame after being split into c64_flop_misc and c64_flop_orig.

Is it possible to remove this software list from mameui64 in the next release?

best regards

**Comment by Robbbert** [comment]
That file is not in the repository, so I could not have added it. If you check my version at https://messui.1emulation.com, you'll see that the unwanted file is not there.

However, I checked the package that comes from mameui.info, and it is there. That package is not made by me, but rather by the webmaster there. I've left him a note.

**Comment by mamecodemonkey** [comment]
mameui.info is not the official website of mameui64, but the one on 1emulation.com is, correct?
It's confusing.

Why are there 2 websites?

**Comment by Robbbert** [comment]
The executable found on both sites is the same, but the other files in the package could be different. There's historical reasons for that, which I won't go into. I think we're done here.
