### ISSUE TITLE
Compiling MAMEUI64 for 32/64 bit OS

### ISSUE THREAD

**Issue by mamecodemonkey** [Robbbert/mameui#49]
Dear MAMEUI64 dev,

I searched a long time on various forums to find a guide to compile MAMEUI64.
Nothing which I found is working. 

Is it possible to write a guide on how to compile MAMEUI64 , put it on github or include it in the source code somewhere?
Please include used compiler and version and all requirements I need to do.

best regards

**Comment by Robbbert** [comment]
The answers to your questions are on the release site http://messui.1emulation.com/

**Comment by mamecodemonkey** [comment]
I'm a beginner with GCC and I see MAME uses MSYS2 https://www.mamedev.org/tools/

Since MAMEUI64 is just a UI layer on top of MAME, do I also need MSYS2 to compile MAMEUI64?

**Comment by Robbbert** [comment]
I don't use MSYS2, but you can if you want to. But please take note of what's written on the website:
"_You can compile your own binary by accessing the listed github repository, and using the tools and options listed above. This is provided as a license requirement only. Compile issues are not supported. You're on your own_."
So, as you can see, I do NOT provide assistance with compiling, and you have to work it out yourself.

**Comment by mamecodemonkey** [comment]
Hi

It's also not possible to write a brief summary on the website how you compile it? (without further assistance)
There is nothing explained.

I don't understand why you don't give any other explanation (except the GCC version).

**Comment by Robbbert** [comment]
That's the way it is. I can't possibly support executables not compiled by me.
