### ISSUE TITLE
compiling with msys2 or not?

### ISSUE THREAD

**Issue by ghost** [Robbbert/mameui#55]
I'm trying to compile mameui.

I have 2 questions about it:

- do I need to use msys2 as mame uses or only a GCC compiler? This one: https://www.mamedev.org/tools/
If it's GCC only, what version should work or is recommended?

- is the make command just this?

make OSD=messui

Do you know what make command to add to use all CPU cores when compiling?

All the best

**Comment by bigmistercactus** [comment]
As an additional question: is there also a command to generate a visual studio solution for mameui as used in the mame makefile?
Look here: https://wiki.mamedev.org/index.php/Building_MAME_using_Microsoft_Visual_Studio_compilers

**Comment by Robbbert** [comment]
Jessica Jones, what a pleasure.

I use and recommend standalone GCC ver 10.1, which I understand is difficult to find now. The make command is documented on my website.

Microsoft compilers cannot be used. You'll get compilation errors because they don't support VLAs.

**Comment by bigmistercactus** [comment]
sorry, what are VLAs?

Why is GCC 11 not used?

**Comment by Robbbert** [comment]
Looks like you deleted yourself. Closing.
