### ISSUE TITLE
Cursor does not lock inside window in Windowed mode

### ISSUE THREAD

**Issue by Superjustinbros** [Robbbert/mameui#56]
Since a few years ago, when playing a game in MAMEUI with a mouse (specifically, paddle and trackball games), the mouse can freely leave the game window and interact/click on desktop elements. I have looked all over the UI's settings to find a fix for this, and I cannot find a single option for it inside the default game properties menus.

**Comment by Robbbert** [comment]
It's intentional. If you're in windowed mode it acts like any other windows app.
You need to run the game in full-screen mode.

**Comment by Superjustinbros** [comment]
So there's no way to re-implement a toggle in the settings menu that keeps the cursor inside the window at all times unless you pause or press the Windows key? I prefer to run applications in windowed mode over going fullscreen.

**Comment by Gravityzwell** [comment]
Not the best answer, but I have 2 or 3 different ways with Autohotkey. The primary is freezing the cursor in the middle of the window with BlockInput MouseMove. Lightgun games continue to work as expected, without the cursor running all over the desktop. Other games without mouse input are not affected. For something that has an internal cursor, e.g., chess games, those need an alternative method polling for the window boundaries. Good enough for me and MUCH better than it was.
