### ISSUE TITLE
Mameui and Messui -mame software list- does not change the loading software

### ISSUE THREAD

**Issue by deejayses** [Robbbert/mameui#58]
Hello, I don't really know where to indicate this problem.
the problem only occurs with mame software list, and with mameui and messui (mame works fine)

when I select a system, for example zxspectrum (it also happens with consoles) the first load-reading of the software is correct, I proceed to load it and it works perfectly.
The problem is when selecting another software, by default the previous software is loaded without the possibility of changing, choose the software you choose.
If it allows me to change the diskette or cartridge, in the mame menu (tab), that is, manually.
Some similar problema i see in another forum without resolution

https://www.mameworld.info/ubbthreads/showthreaded.php?Cat&Number=390240&page=1&view=expanded&sb=5&o&fpart=1&vc=1

Any configuration ideas?

**Comment by Robbbert** [comment]
Unable to reproduce. Most likely a configuration problem.

**Comment by Robbbert** [comment]
Nothing heard, closed.
