### ISSUE TITLE
Cannot display new History.XML file format in MEMEUI.exe (64 bit version)

### ISSUE THREAD

**Issue by Toncino** [Robbbert/mameui#60]
Ah all,

as written in the subject, MameUI (64 bit) does not correctly read the History.XML file format. I can correctly display the History.dat file, but it looks like this format will not be supported anymore.

I copied the .XML version in the dat folder as per instruction with no luck.

FYI, I use the MameUI version downloaded form [IV/Play and MameUI Home Page](http://www.mameui.info/)

Any support will be indeed appreciated!

**Comment by Robbbert** [comment]
As mentioned many times, History.XML will not be supported - ever.

**Comment by Toncino** [comment]
I'm sorry to hear that, supporting XML will it require a lot of rewriting of the codes? Or is there any specific reason why you don't want to support that?
